services:
  css:
    image: solidproject/community-server:6.0.0-alpha.0
    restart: always
    container_name: solid-indexer_css
    environment:
      - CSS_BASE_URL=http://localhost:8000
      - CSS_PORT=8000
      - CSS_CONFIG=config/file-acp-notifications-all.json
    volumes:
      - css:/data
      - ./css/file-acp-notifications-all.json:/community-server/config/file-acp-notifications-all.json
    ports:
      - 8000:8000

volumes:
  css:
    name: solid-indexer_css
